"""empty message

Revision ID: 23212bd3624f
Revises: 4b1a40a17772
Create Date: 2025-05-09 12:29:12.409798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23212bd3624f'
down_revision = '4b1a40a17772'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto__carrefour', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cantidad', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto__carrefour', schema=None) as batch_op:
        batch_op.drop_column('cantidad')

    # ### end Alembic commands ###
