"""empty message

Revision ID: 4b1a40a17772
Revises: c7a7e11ca8b1
Create Date: 2025-04-24 11:25:45.153781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b1a40a17772'
down_revision = 'c7a7e11ca8b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventario', schema=None) as batch_op:
        batch_op.alter_column('numero',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventario', schema=None) as batch_op:
        batch_op.alter_column('numero',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
