"""Añade campo tipo a movimiento

Revision ID: c7a7e11ca8b1
Revises: 
Create Date: 2025-04-23 09:30:56.535553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7a7e11ca8b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventario', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=False)

    with op.batch_alter_table('movimiento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.Enum('Añadir', 'Editar', 'Eliminar', name='tipo_movimiento'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimiento', schema=None) as batch_op:
        batch_op.drop_column('tipo')

    with op.batch_alter_table('inventario', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
